#!/usr/bin/env bash

# Name:     sb-forecast
# Author:   David Vogel <david@davidvogel.xyz>
# Date:     2026 Jan 31, Sat
# License:  GPL v3.0
# Desc:     `sb-forecast` displays local temperature data.

URL="${WTTRURL:-wttr.in/?m}"
WEATHERREPORT="${XDG_CACHE_HOME:-$HOME/.cache}/weatherreport"

# Forecast should be updated only once a day.
checkforecast() {
    if [[ -s "$WEATHERREPORT" ]]; then
        [ "$(stat -c %y "$WEATHERREPORT" 2>/dev/null | cut -d' ' -f1)" \
            = "$(date '+%Y-%m-%d')" ]
    else
        return 1
    fi
}

# Get a weather report from 'wttr.in' and save it locally.
getforecast() {
    timeout --signal=1 2s curl -sf "$URL/$LOCATION" > "$WEATHERREPORT" \
        || exit 1
}

readfile() {
    weatherdata="$(cat "$WEATHERREPORT")"
}

getprecipchance() {
    echo "$weatherdata" |
        sed '16q;d' |                       # Extract line 16 from file
        grep -wo "[0-9]*%" |                # Find a sequence of digits followed by '%'
        sort -rn |                          # Sort in descending order
        head -1q                            # Extract first line
}

getdailyhighlow() {
    echo "$weatherdata" |
        sed '13q;d' |                       # Extract line 13 from file
        grep -o "m\\([-+]\\)*[0-9]\\+" |    # Find temperatures in the format "m<signed number>"
        sed 's/[+m]//g' |                   # Remove '+' and 'm'
        sort -g |                           # Sort in ascending order
        sed -e 1b -e '$!d'                  # Extract the first and last lines
}

# Displays today's precipication chance (☔), and daily low (🥶) and high (🌞).
# Usually intended for the statusbar.
showweather() {
    readfile
    printf "☔ %s 🥶 %s° 🌞 %s°\n" "$(getprecipchance)" $(getdailyhighlow)
}

main() {
    case $BLOCK_BUTTON in
        1) setsid -f "$TERMINAL" -e less -Sf "$WEATHERREPORT" ;;
        2) getforecast && showweather ;;
        3) notify-send "🌈 Weather module" "\- Left click for full forecast.
- Middle click to update forecast.
☔: Chance of rain/snow
🥶: Daily low
🌞: Daily high" ;;
        6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
    esac

    checkforecast || getforecast
    showweather
}

main
