#!/usr/bin/env bash

# `xrandr` takes a decimal as an argument
# if the brightness arg is 100%, then there is no need for decimal
# otherwise, represent as decimal
if [[ "$1" == 10 ]]; then
    percent="1"
else
    percent="0.${1}"
fi

# if the second arg exists, and is `night`, then set "night light"
# otherwise, keep gamma levels the same
if [[ "$2" == "night" ]]; then
    gamma="1.0:0.95:0.85"
else
    gamma="1.0:1.0:1.0"
fi

export DISPLAY=:0

mon=$(xrandr | grep " connected")
mon=(${mon[@]%% *})

notif() {
    # `-h string:bgcolor:#ebcb8b`
    notify-send -t 3000 "Brightness adjusted to ${1}0%!"
}

dim() {
    while read m; do
        xrandr --output "$m" --brightness "$percent" --gamma "$gamma"
    done <<<"$mon"
}

dim && notif "$1"
