#!/usr/bin/env bash

# Name:     dmenuunicode
# Author:   David Vogel <david@davidvogel.xyz>
# Date:     2026 Jan 17, Sat
# License:  GPL v3.0
# Desc:     `dmenuunicode` provides a menu to copy emojis into the clipboard.

main() {
    # Pipe list of emojis into `dmenu`; get user input
    local choice="$(cat ~/.local/share/emoji | dmenu -i -l 30)"
    choice="${choice%% *}"

    # Exit if no emoji is chosen
    ! [[ "$choice" ]] && exit

    # If argument, insert the emoji
    # If no argument, add emoji to clipboard
    if [[ "$1" ]]; then
        xdotool type "$choice"
    else
        printf "%s" "$choice" | xclip -selection clipboard
        notify-send "\"$choice\" copied to clipboard!" &
    fi
}

main
