#!/usr/bin/env bash

# Name:     recompile-wm
# Author:   David Vogel <david@davidvogel.xyz>
# Date:     2025 Oct 17, Fri
# License:  GPL v3.0
# Desc:     `recompile-wm` is a script for recompiling software for DWM.

SRC_DIR="${HOME}/.local/src"

list_to_recompile=(
    "dmenu"
    "dwm"
    "dwmblocks"
    "st"
)

# Prints provided message to STDERR; then, exits with return code `1`
error() {
    echo "$1" >&2 \
        && exit 1
}

recompile-loop() {
    for d in "${list_to_recompile[@]}"; do
        if [[ -d "${SRC_DIR}/${d}" ]]; then
            cd "${SRC_DIR}/${d}"

            echo "[INFO]: Recompiling \`${d}\`..."
            sudo make install > /dev/null 2>&1 \
                && echo "[INFO]: Successfully recompiled \`${d}\`!" \
                || error "[ERROR]: Failed to recompile \`${d}\`. Exiting now."

            cd - > /dev/null 2>&1
        fi
    done
}

main() {
    recompile-loop

    echo
    echo "[INFO]: Successfully recompiled all software!"
}

main
